### ISSUE TITLE
Add run parameter to set maximum number of cores/nodes

### ISSUE THREAD

**Issue by rezib** [edf-hpc/unclebench#11]
When a user run a benchmark, it could use quite a lot of cores/nodes. It should be possible to limit the number of cores/nodes so that all runs above those limits are discarded. Eg:

```
$ ubench run -b hpcc --max-nodes=8
$ ubench run -b hpcc --max-cores=96
```

**Comment by rezib** [comment]
This feature would be more usefull if #10 is also developed.

**Comment by rezib** [comment]
This one should be considered low priority, it should not be that useful indeed if platform description files are well defined.

**Comment by camilo1729** [comment]
I think it is not relevant any more given the possible of using `-w` to specify the number of nodes. For example: `ubench run -b hpcc -p zbook15 -w 2 4 8`
