### ISSUE TITLE
ubench resultt option to show the paths were results were produced

### ISSUE THREAD

**Issue by camilo1729** [edf-hpc/unclebench#40]
Sometimes a benchmark execution is composed of several independent executions. For example when executing a benchmark with different amount of nodes, we will produce several directories with the outputs of jobs executions. For debugging purposes it will be helpful to have the path to of these directories when we show the results with the command 'ubench results'

**Comment by saidamirouche** [comment]
Fixed from commit 046c542bf7635965670d9d2e8af499a4121d6fd9
