### ISSUE TITLE
Minor improvements

### ISSUE THREAD

**Issue by erothe** [edf-hpc/unclebench#46]
- Not all home path's follow the syntax `/home/userid`. To find the user's home directory the `pwd` package should be used instead of the hard coded syntax `/home/userid` (see ubench_config.py). The home directory can be retrieved using `pwd.getpwuid(os.getuid()).pw_dir` ;
- Both files `setup.py` and `_version.py` have hard coded version id's making it easy to forget to update them when a new version is to be created. An additional step in the packaging procedure is a simple solution or something more fancy can be coded ;
- There is an odd UBENCH_CONF_DIR directory that seems not to be used anywhere. This directory is defined with a trailing slash, contrary to other directory definitions.

**Comment by rezib** [comment]
Hi @erothe, could you please split this issue into 3 atomic issues with meaningful titles? This makes bug triaging and tracking much easier.

**Comment by erothe** [comment]
The 3 points identified above in this issue were copied to three independent issues: #47 , #48 and #49 . I will close this issue.
