### ISSUE TITLE
implement a method to bench all (available) nodes in parallel

### ISSUE THREAD

**Issue by rezib** [edf-hpc/unclebench#5]
The software should be able to run a bench on all (available) nodes invidually, in parallel without the need to wait for one result before running the bench on the following node. Eg.:

```
# ubench run -b hpcc -w @all
```

Unclebench should be able to get all available nodes in the job scheduler (excluding automatically the down/draining nodes), and submit all needed jobs itself.

Then, get the results with this command:

```
# ubench result -b hpcc
node001: <results>
node002: <results>
```

This result command should also be able to tell if jobs are still pending, if the nodes were down or draining during the `run` command, and so on.

**Comment by pierretr** [comment]
Available since version 0.2.0.
