### ISSUE TITLE
show the result of previous runs

### ISSUE THREAD

**Issue by rezib** [edf-hpc/unclebench#6]
The `results` command is only able to print the result of the previous benchmark run. It would be nice if it is able to show the result of the previous runs.

One way to do this would be to generate one UUID per run, with associated metadata such as run datetime, targeted nodes, and so on. Then, this command could give the list of runs:

```
$ ubench list -b hpcc
UUID  date                nodes
----- ------------------- --------------
<id1> 2016-03-29 14:05:00 node[01-10]
<id2> 2016-03-29 14:06:00 node[01-03]
```

Then, the `results` command show the results of the last run by default, but users are able to give a _run UUID_ in parameter to get the previous results. For example:

```
$ ubench results -b hpcc # give last run results
$ ubench results -b hpcc -u <id2> # give the results of run <id2>
```

**Comment by pierretr** [comment]
Available since version 0.2.0.
