### ISSUE TITLE
unclebench should be able to recognize the cluster it is running on

### ISSUE THREAD

**Issue by rezib** [edf-hpc/unclebench#8]
The `run` command asks for a cluster name in parameter to know which plaftorm description file it should refers to. Unclebench should be able to recognize to cluster it is running on, typically based on the hostname of the frontend, to set the default value of the `-p` parameter.

However, the parameter should stay in place, it must only be a default value. The users should be able to set it the cluster name in parameter anyway, and do something wrong, if they want to.

**Comment by pierretr** [comment]
Available since version 0.2.0.
